name: Update Sponsors
on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *

jobs:
  update-sponsors:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: data
      - name: Update
        uses: ./.github/actions/update-sponsors
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit
        uses: EndBug/add-and-commit@v7
        with:
          add: data.json
          author_name: Automated
          author_email: automated@papermc.io
          branch: data
          message: Sponsor Update
